# Generated by Django 5.0.6 on 2024-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicioapp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
